def get_schema(endpoint):
    if endpoint == 'campaign':
        fields = [
            'id',
            'campaign_title',
            'type',
            'list_id',
            'list_is_active',
            'list_name',
            'subject_line',
            'preview_text',
            'emails_sent',
            'abuse_reports',
            'unsubscribed',
            'send_time',
            # 'timeseries',
            'bounces.hard_bounces',
            'bounces.soft_bounces',
            'bounces.syntax_errors',
            'forwards.forwards_count',
            'forwards.forwards_opens',
            'opens.opens_total',
            'opens.unique_opens',
            'opens.open_rate',
            'opens.last_open',
            'clicks.clicks_total',
            'clicks.unique_clicks',
            'clicks.unique_subscriber_clicks',
            'clicks.click_rate',
            'clicks.last_click',
            # 'facebook_likes.recipient_likes',
            # 'facebook_likes.unique_likes',
            # 'facebook_likes.facebook_likes',
            # 'industry_stats.type',
            # 'industry_stats.open_rate',
            # 'industry_stats.click_rate',
            # 'industry_stats.bounce_rate',
            # 'industry_stats.unopen_rate',
            # 'industry_stats.unsub_rate',
            # 'industry_stats.abuse_rate',
            'list_stats.sub_rate',
            'list_stats.unsub_rate',
            'list_stats.open_rate',
            'list_stats.click_rate',
            'ecommerce.total_orders',
            'ecommerce.total_spent',
            'ecommerce.total_revenue',
            'ecommerce.currency_code',
            # 'delivery_status.enabled',
            # 'delivery_status.can_cancel',
            # 'delivery_status.status',
            # 'delivery_status.emails_sent',
            # 'delivery_status.emails_canceled'
        ]

    elif endpoint == 'list_growth':
        fields = [
            "list_id",
            "month",
            "existing",
            "imports",
            "optins",
            "subscribed",
            "unsubscribed",
            "reconfirm",
            "cleaned",
            "pending",
            "deleted",
            "transactional"
        ]

    elif endpoint == 'orders':
        fields = [
            'id',
            'store_id',
            'campaign_id',
            'landing_site',
            'financial_status',
            'fulfillment_status',
            'currency_code',
            'order_total',
            'order_url',
            'discount_total',
            'tax_total',
            'shipping_total',
            # 'tracking_code',
            'processed_at_foreign',
            'cancelled_at_foreign',
            'updated_at_foreign',
            'promos',
            # 'lines',
            # 'tracking_number',
            # 'tracking_carrier',
            # 'tracking_url',
            'customer.id',
            'customer.email_address',
            # 'customer.opt_in_status',
            # 'customer.company',
            # 'customer.first_name',
            # 'customer.last_name',
            # 'customer.orders_count',
            # 'customer.total_spent',
            # 'customer.address.address1',
            # 'customer.address.address2',
            # 'customer.address.city',
            # 'customer.address.province',
            # 'customer.address.province_code',
            # 'customer.address.postal_code',
            # 'customer.address.country',
            # 'customer.address.country_code',
            # 'customer.created_at',
            # 'customer.updated_at',
            # 'customer._links',
            # 'shipping_address.name',
            # 'shipping_address.address1',
            # 'shipping_address.address2',
            'shipping_address.city',
            # 'shipping_address.province',
            # 'shipping_address.province_code',
            # 'shipping_address.postal_code',
            'shipping_address.country',
            # 'shipping_address.country_code',
            # 'shipping_address.longitude',
            # 'shipping_address.latitude',
            # 'shipping_address.phone',
            # 'shipping_address.company',
            # 'billing_address.name',
            # 'billing_address.address1',
            # 'billing_address.address2',
            # 'billing_address.city',
            # 'billing_address.province',
            # 'billing_address.province_code',
            # 'billing_address.postal_code',
            # 'billing_address.country',
            # 'billing_address.country_code',
            # 'billing_address.longitude',
            # 'billing_address.latitude',
            # 'billing_address.phone',
            # 'billing_address.company',
            # 'outreach.id',
            # 'outreach.name',
            # 'outreach.type',
            # 'outreach.published_time'
        ]

    elif endpoint == 'lines':
        fields = [
            'id',
            'product_id',
            'product_title',
            'product_variant_id',
            'product_variant_title',
            'image_url',
            'quantity',
            'price',
            'discount'
        ]

    elif endpoint == 'products':
        fields = [
            'id',
            'currency_code',
            'title',
            'handle',
            'url',
            'description',
            'type',
            'vendor',
            'image_url',
            # 'variants',
            # 'images',
            'published_at_foreign'
        ]

    elif endpoint == 'variants':
        fields = [
            'id',
            'title',
            'url',
            'sku',
            'price',
            'inventory_quantity',
            # 'image_url',
            # 'backorders',
            # 'visibility',
            'created_at',
            'updated_at'
        ]

    elif endpoint == 'members':
        fields = [
            'id',
            # 'email_address',
            'unique_email_id',
            'contact_id',
            # 'full_name',
            # 'web_id',
            'email_type',
            'status',
            # 'consents_to_one_to_one_messaging',
            # 'ip_signup',
            # 'timestamp_signup',
            # 'ip_opt',
            # 'timestamp_opt',
            'member_rating',
            'last_changed',
            'language',
            'vip',
            'email_client',
            'source',
            # 'tags_count',
            # 'tags',
            'list_id',
            # 'merge_fields.FNAME',
            # 'merge_fields.LNAME',
            # 'merge_fields.ADDRESS',
            # 'merge_fields.PHONE',
            # 'merge_fields.BIRTHDAY',
            # 'merge_fields.INTEREST',
            # 'merge_fields.MYGIFTCARD',
            'stats.avg_open_rate',
            'stats.avg_click_rate',
            'stats.ecommerce_data.total_revenue',
            'stats.ecommerce_data.number_of_orders',
            'stats.ecommerce_data.currency_code',
            # 'location.latitude',
            # 'location.longitude',
            # 'location.gmtoff',
            # 'location.dstoff',
            # 'location.country_code',
            # 'location.timezone',
            # 'location.region',
            # 'merge_fields.ADDRESS.addr1',
            # 'merge_fields.ADDRESS.addr2',
            # 'merge_fields.ADDRESS.city',
            # 'merge_fields.ADDRESS.state',
            # 'merge_fields.ADDRESS.zip',
            # 'merge_fields.ADDRESS.country'
        ]

    elif endpoint == 'emails':
        fields = [
            'campaign_id',
            'list_id',
            'email_id',
            'activity'
        ]

    else:
        fields = None

    return fields
